services:
  - type: web
    name: cantex
    env: python
    repo: https://github.com/muthukumaran8661/CanteX
    buildCommand: pip install -r project/requirements.txt
    startCommand: cd project && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "0"
